spring:
  profiles:
    active: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://zrodo2015.mysql.rds.aliyuncs.com:3306/hebeizonghe?useUnicode=true&amp;characterEncoding=utf-8
      username: hebeizonghe
      password: HeBeiZH
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000
  #文件上传大小限制
  http:
      multipart:
          max-file-size: 50MB
          max-request-size: 500MB
  # 连接池配置
  session:
    store-type: redis
  redis:
    host: www.zrodo.com
    port: 6379
    password: zrodo123456
    pool:
      max-active: 20
      min-idle: 2
logging:
  path: exam.log
  level:
    root: info
##自定义配置
token:
  expire:
    time: 60
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
application:
  hello: HelloAngel From Application